#!/bin/bash

echo "🔐 AWS Credentials Setup"
echo ""
echo "You need to configure valid AWS credentials to push to ECR."
echo ""
echo "Option 1: Configure via AWS CLI (recommended)"
echo "  Run: aws configure"
echo "  Enter your:"
echo "    - AWS Access Key ID"
echo "    - AWS Secret Access Key"  
echo "    - Default region: eu-central-1"
echo "    - Default output format: json"
echo ""
echo "Option 2: Use AWS SSO (if your organization uses it)"
echo "  Run: aws configure sso"
echo ""
echo "Option 3: Set environment variables temporarily"
echo "  export AWS_ACCESS_KEY_ID=your-access-key"
echo "  export AWS_SECRET_ACCESS_KEY=your-secret-key"
echo "  export AWS_DEFAULT_REGION=eu-central-1"
echo ""
echo "After configuring credentials, run ./push-to-ecr.sh again"
